/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code401challenges.fifo_animal_shelter;

public class AnimalShelter {

    public Node cats;
    public Node dogs;
    public AnimalShelter (Animal animal){
        //cats queue
        Node cats;
        //dogs queue
        Node dogs;

    }
    public void enqueue(Animal animal){
        if (animal.type.equals("dog")){
            Node node = new Node(animal, this.dogs);
            this.dogs = node;
            return;
        }else if (animal.type.equals("cat")){
            Node node = new Node(animal, this.cats);
            this.cats = node;
            return;
        }
        throw new IllegalArgumentException("This shelter isn't equipped to handle that kind of animal, Franks Sausage factory is accepting drop off's");
    }
    public Animal dequeue(String pref){
        if(pref.equals("dog")){
            return getPet(this.dogs, "dog");
        }
        else if (pref.equals("cat")){
            return getPet(this.cats, "cat");
        }
        else{
            return null;
        }

    }

    private Animal getPet(Node petsLinkedList, String type) {
        Animal res = null;
        Node current = petsLinkedList;
        Node prev = null;
        if (current == null){
            return null;
        }

        while(current.next != null){
            prev = current;
            current = current.next;
        }
        res = current.value;
        if(prev == null){
            if( type.equals("dog")){
                this.dogs = null;
            } else {
                this.cats = null;
            }

        } else {
            prev.next = null;
        }
        return res;
    }

}
