/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code401challenges;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void test_insertShiftArray(){
        ArrayShift arrayShift = new ArrayShift();
        int[]testArray = new int[]{1,2,3,4,5,6};
        int[]result = new int[]{1,2,3,99,4,5,6};
        assertArrayEquals("New Value is inserted into the array", arrayShift.insertShiftArray(testArray, 99),result);

    }
}
